version: "3.9"

services:
  web:
    image: codster177/see-key-site:latest
    ports:
      - "80:3000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/dev.db
    restart: always

volumes:
  sqlite_data: